import React from 'react'

function Assignment() {
  return (
    <div>
        <h1>
        Question(string)/required	Total Marks	Skill Tags	Sub Tags	Tag Level	Solution/optional	File Upload (string)/optional	Created At(datetime)
Create a program to calculate the sum of all the even numbers till the number n.	2	Python	Loops, Conditional Statement	beginner			
Create a program to calculate the sum of all the prime numbers till the number n.	2	Python	Loops, Conditional Statement	beginner			
Print a diamond on the screen through star signs.	2	Python	Loops, Conditional Statement	beginner			
"Write a program to print numbers in a diamond pattern.
Note :Each number should represent the same as the given example below.
Example :
         Input :5
          Output :            1
                                 212
                               32123
                                 212
                                   1
"	5	Python	Loops, Conditional Statement	intermediate			
"Print fibonacci series using loops.
A Fibonacci sequence is the integer sequence of 0, 1, 1, 2, 3, 5, 8.
The first two terms are 0 and 1. All other terms are obtained by adding the preceding two terms.
"	5	Python	Loops, Conditional Statement	intermediate			
"Write a python program to print the pattern of number as given below
0
0 1
0 1 2
0 1 2 3.
"	5	Python	Loops, Conditional Statement	intermediate			
"Write a python program to sort a list in ascending order.
 List =[2,4,1,3]
 sortedList =[1,2,3,4]
"	5	Python	Loops, Conditional Statement	intermediate			
"Write a python program to read a sample created file and also write in the same file.
 Note : write in a self-created file , the following things : “Hi , I am learning python.”"	2	Python	File Systems	beginner			
Create a console based URL shortener application in python. The user will enter a URL, and by applying custom encoding algorithm, the application will transform the url.	7	Python	Loops, Conditional Statement	hard			
" Write a program to count a vowel in a given string.
  Input : Sunday
  Output : 2 (u,a)
"	2	Python	Loops, Conditional Statement	beginner			
"Write a program where you have to take a number as in input and find the length of the given number. 
Note : You cannot use built in methods like len.
Input :2341
Output:4
"	5	Python	Loops, Conditional Statement	intermediate			
"Write a program to get the fibonacci series between a given range from 1 to given range.
Note : A series of numbers in which each number is the sum of the two preceding numbers. The simplest is the series 1, 1, 2, 3, 5, 8, etc."	5	Python	Loops, Conditional Statement	intermediate			
Write a program to print a diamond pattern.	5	Python	Loops, Conditional Statement	intermediate			
"Menu Driven Calculator Application
Develop a console-based menu driven application through which user can perform different mathematical operations. When the user will launch the application, a menu should be displayed which should contain the following options:
Factorial
Palindrome
Fibonacci
Table of a given number
"	7	Python	Loops, Conditional Statement	hard			
"Question 1: Create a Billing Application where two files needs to be maintained as follows :
1: Product_details.csv : This file contains product detail in following table  format
         
Product_id
Product_name
Product_price
1
Thumbs Up
30 Rs,
2
Pepsi
25 Rs.


2:Billing_details.csv : This file will contain  the details in following table  format :
     
Customer_name
Product_name
Quantity
Total



Functionality :  User will take input for the following things :
                          1: Choice of product as given  in product_details.csv file.
                           2: quantity of the named product to be specified.
                     3: Customer_name choosing the product.
 
After taking all the input , Total will be calculated with the price of the product chosen from the Product_details.csv file and the quantity mentioned by the customer.
Lastly,write the all billing details in the Billing_details.csv file in the given format.
"	15	Python	File Systems	hard			
"Create a Invoice Generating Application where three files need to be maintained as follows :
1: Product_details.csv : This file contains details of the product ,and needs to be maintained as given in Question 1. Addition of some sample product would be appropriate from User.
2: Invoice.csv : This file would contain data as follows :


Invoice_id(autogenerated)
Product_name 
Quantity 
Total


Note : In Invoice table the Invoice_id will be auto generated and for a particular customer an invoice will be generated.
An Invoice may contain multiple products added by the customer with a given quantity and its total being mapped with the product.

3: An Html File needs to be created based on the Invoice_id generated for a particular Customer as Invoice.html.
Note : An Html File will be generated when a particular customer quits choosing a product from a given product_details.csv file and proceeds for billing.

Note : Any confusion regarding the assignment , kindly raise a ticket we will assist you .

"	15	Python	File Systems	hard			
"
Given are the below links for Github quizzes and Mini Projects , which needs to completed:


Git Quiz Links : 

Link 1 : https://www.codecademy.com/courses/learn-git/quizzes/git-1
Link 2 : https://www.codecademy.com/courses/learn-git/quizzes/github-flow-quiz

Git Project Links :
Link 1 : https://www.codecademy.com/courses/learn-git/projects/snapfit-robots
Link 2: https://www.codecademy.com/courses/learn-git/projects/manhattan-zoo

"	10	Git,Github	Git,Github	intermediate			
"Create a travel blog of  your favorite place which consists of YouTube videos and google map location of that particular place and also do the styling using CSS.
Figma basic design : https://www.figma.com/file/fWwZvVeXtFudCezaJAUzA4/TRAVEL-BLOG?node-id=1%3A4
"	10	HTML/CSS	HTML,CSS	intermediate			
https://docs.google.com/spreadsheets/d/1Ko91tafaU6Yis3lB7Nex3XGH9RUyN_OH/edit#gid=274224664	10	HTML/CSS	HTML,CSS	intermediate			
https://docs.google.com/spreadsheets/d/1KQrgusuAHbOS1LTwz0BQFA5sMkanlN2N/edit#gid=224327286	20	HTML/CSS	HTML,CSS	intermediate			
https://docs.google.com/document/d/1zDp7WDGb5vKPYhofrFn1v_B3Ju2s-gFz/edit	20	HTML/CSS	HTML,CSS	intermediate			
" Display your strong HTML skills and create a photography website where you can post all the pictures with the following specifications:-
 
a) Add the business name at the top with a picture describing the intent of your website. 
b) Add a specific link that people click to have a look at your previous work. This click will lead them directly to the section of photos on the     same page.
c) Include navigation to the contact us page including a contact us form.
d)  Include navigation to a courses page that includes a list of various photography courses provided.
"	20	HTML/CSS	HTML,CSS	Hard			
"In this assignment, you will use HTML AND CSS to create a portfolio website. Throughout the training you will create various programs that will be added to your portfolio. At the end of the training, you will have a complete website which will showcase all of your hard work!
Create a portfolio home page which demonstrate your projects done so far(you can link your existing  projects or simply some pictures).
Note:
Header: The header of the webpage includes the navigation buttons. You will link these buttons to their respective web pages later in this assignment. The Nav buttons should be spaced to look appealing.
Sections: The website should include three sections, first one displaying  your introduction and second  displaying your project work and the third section will include the social media links."	20	HTML/CSS	HTML,CSS	Hard			
"Create an attractive simple login html page , where the input boxes have a css hover effect to enhance the user interface of the login page.
The submit button of the login page should be followed  by a simple loading spinner , with a text saying waiting for the network.
https://docs.google.com/document/d/1vE3GIaWfaJ72sU3moMXNdA8Nj5SxOGrV4p2M7hRTBl0/edit


Note : 
Input boxes must have hover effects on them.
There should be a simple loading spinner with text below it stating “waiting for the network.”
"	20	HTML/CSS	HTML,CSS	Hard			
"Create an empty webpage.
 
Create an XML file in your project folder with the following format:-
 
{/* < restaurant name=""yellow chilli"" address=""new delhi"" lat=""47.608940"" lng=""-122.340141"" type=""sitdown""/>
 
Use AJAX to load the file into your page.
 
Create a <ul>. For each <restaurant>, create a <li> with the name and address of the restaurant. Change the color of the text depending on the type of the restaurant (“sit down” or “bar”).
"	15	Javascript	AJAX	intermediate			 */}
"Find an API that provides you with the population figure of a given country.
When the user has entered the name of a country and press add, your application should retrieve the population data from the API, and add the name of the country and its population figure to the list.
If the user enters something that is not recognized as a country by the API, it should not be added to the list, and an appropriate message is shown to the user. You can display this message by using a simple alert box.
"	15	Javascript	Javascript,HTML,CSS	intermediate			
"Assignment based on AJAX Scrolling

Problem Statement : 
Use a file named “blog.txt” , to store name and blog of users in given format  :
    <span>Username:Sam </span>
     <p> Hii my first blog </p>

Store at least for 10 different usernames.
Use an AJAX to load this file on your html when the user scrolls down, on the div in which you are showing the data.

Note : You may use some hard coded Username and blog in your Html div, to make it scrollable and then call the Ajax function onscroll event.

"	15	Javascript	AJAX	Hard			
"Game Searching Application

Develop a Single-page Game Searching Application that allows user to search a particular famous game and show games similar to the search game. There should be a search bar and a search button where user will be able to search for a particular game. User can search for multiple famous games. 
Suggested UI Elements:- 
Search Bar: - It will be displayed on top of the webpage where user will be able to write a game name.
Search Button: - It will be displayed along the Search Bar. So that user can click this button to view the similar games.

The URL for the used API -https://api.rawg.io/api/games?key=5c14b272c6594eb7857bb4a774e32aef&search=
Technology used:
Front End: 
•        HTML
•        CSS
•        JS
Features:
•        User 
         Functionality for searching games




"	20	Javascript	Javascript,HTML,CSS	Hard			
"Write a program to print to duplicate elements of an array .
 Sample_input  : [1,1,2,3,3,4,5,6,6]
 Sample_ouptut : 1,3,6
"	5	Javascript 	Loops, Conditional Statement	intermediate			
"Write a program to find the element with highest frequency in an array.
Sample_input :[1,2,4,3,2,4,2,5,7,2]
Sample_output :2
"	5	Javascript	Loops, Conditional Statement	intermediate			
"Write a program to check whether a String is palindrome or not .
Note :A Palindrome String is a string that is the same after the reverse .
Example : LOL , MADAM.
"	5	Javascript	Loops, Conditional Statement	intermediate			
"Write a program to sort a string in alphabetical order. 
           Example : input = cae
                            output=ace
"	5	Javascript	Loops, Conditional Statement	intermediate			
"Write a program to check whether the given string is a pangram or not.
       Note: A pangram is a sentence which contains all the elements of the English alphabet.
       Example : this is my country.
"	5	Javascript	Loops, Conditional Statement	intermediate			
"Write a program to find duplicates from the unsorted array.
                  Arr = [1,2,3,3,2,8,8,5,6]
"	5	Javascript	Array,Loops,Conditional	intermediate			
Y2K problem: Databases written in 1970's used 2-digit fields to represent the year e.g., 77, 80 instead of 1977, 1980.However with the year 2000 nearby all these fields had to be changed to be 4-digit date. Write a program to change a given 2-digit year to a 4-digit year. Remember that if the 2-digit number is less than 35 it means it’s a year in the 2000-year range. E.g., 15 would mean 2015 not 1915. 	5	Javascript	Loops, Conditional Statement	intermediate			
" In a board game, a piece may advance 1-6 tiles forward depending on the number rolled on a six-sided dice. If you advance your piece onto the same tile as another player's piece, both of you earn a bonus.
Can you reach your friend's tile number in the next roll? Create a function that takes your position a and your friend's position b and returns a boolean representation of whether it's possible to earn a bonus on any dice roll.
Examples
possibleBonus(3, 7) ➞ true
possibleBonus(1, 9) ➞ false
possibleBonus(5, 3) ➞ false
Note: -
You cannot move backward (which is why example #3 doesn't work).
If you are already on the same tile, return false, as you would be advancing away.
Expect only positive integer inputs.  
"	5	Javascript	Loops, Conditional Statement	intermediate			
" Create a function that takes two numbers as arguments (num, length) and returns an array of multiples of num until the array length reaches length.
Example: -arrayOfMultiples(12, 10) ➞ [12, 24, 36, 48, 60, 72, 84, 96, 108, 120]
Notes: -Notice that num is also included in the returned array. "	2	Javascript	Array,Loops,Conditional	basic			
"Given an array of positive integers. Find the length of the longest sub-sequence such that elements in the subsequence are consecutive integers, the consecutive numbers can be in any order.
 
Input:
N = 7
{/* a[] = {2,6,1,9,4,5,3} */}
Output:
6
Explanation:The consecutive numbers here are 1, 2, 3, 4, 5, 6. These 6 numbers form the longest consecutive subsquence.
"	5	Javascript	Array,Loops,Conditional	intermediate			
"Given an array, write a function to calculate its depth. Assume that a normal array has a depth of 1.

Examples
depth ([1, 2, 3, 4]) ➞ 1
           depth ([1, [2, [3, 4]]]) ➞ 3
"	5	Javascript	Array,Loops,Conditional	intermediate			
"Given a letter, created a function which returns the nearest vowel to the letter. If two vowels are equidistant to the given letter, return the earlier vowel.

Examples: -
nearestVowel(""b"") ➞ ""a""
nearestVowel(""s"") ➞ ""u""
nearestVowel(""i"") ➞ ""i""

Notes: -
All letters will be given in lowercase.
There will be no alphabet wrapping involved, meaning the closest vowel to ""z"" should return ""u"", not ""a"".
"	5	Javascript	Array,Loops,Conditional	intermediate			
"Write a program to reverse a linked list with a pointer given to head node as given below :
{/* Input : 1->2->3->4
Output:4->3->2->1 */}
"	5	Javascript	Data Structure Algorithm	basic			
"Write a program to create a function which takes two sorted linked lists in ascending order as an input and returns a sorted linked list in ascending order. 
{/* Input:
      list1= 2->1->3
      list2=4->6->5
Output :  sortedlist = 1->2->3->4->5->6 */}
"	5	Javascript	Data Structure Algorithm	intermediate			
" Create a program that accepts the student data as input from the user. The student data should contain the following information:
Student id
Student name
Student marks of 5 subjects
Store this information in a tree data structure where each node represents a single student. The tree should be a binary search tree and use the percentage of each student as criteria for storing objects. After storing all the information, the user will enter the name of a student and his/her grades should be displayed on the screen.
"	5	Javascript	Data Structure Algorithm	intermediate			
"Create a program in which users can enter customer data. The customer data should contain the following information:
Customer Id
Customer Name
Purchase date(dd/mm/yy)
Bill amount
Store this information in a linked list. The program should provide three different options for viewing information:
View all customer data in sorted order based on bill amount
View total purchase amount for a specific year
View details of a specific customer based on name
"	5	Javascript	Data Structure Algorithm	intermediate			
"Phone Directory Application

Create a phone directory application in which user can insert phone records of employees working in an organisation. Each phone record should have the following information:
Employee id
Employee name
Department
Employee Level
L1: Intern
L2: Associate
L3: senior
Store this information in a linked list or tree data structure.

 The application must support following features:
Insert Phone records
Delete specific records
Search/Display records based on:
Name
Department
Employee Level
All records in sorted order based on Employee id/Employee name

"	20	Javascript	Data Structure Algorithm	Hard			
"Write a program that helps the referee start the race.
Code should include the following specifications:
Count down should start from 5
After the count down reaches 1, ""Go"" should appear on the screen
After ""GO"" is shown on the screen Replay button should get enabled to restart the countdown.

NOTE: To achieve the counter animation effect on the countdown, try out your CSS skills.
"	10	HTML/CSS	Animations	intermediate			
							
							
							
							
							
							
							
							
							
        </h1>
    </div>
  )
}

export default Assignment